name: Build iOS

on:
  push:
    branches: [ "*" ]
    tags:     [ "*" ]
  pull_request:

jobs:
  build-ios:
    name: Build
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install tools
      run: |
        brew list automake || brew install automake
        brew list libtool || brew install libtool
        brew list make || brew install make

    - name: Set the correct Xcode version
      run: |
        sudo xcode-select --switch /Applications/Xcode_16.1.app

    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install || echo "Xcode Command Line Tools are already installed"

    - name: Accept Xcode License
      run: sudo xcodebuild -license accept

    - name: Install deps
      working-directory: ${{ github.workspace }}
      env:
        IOS_SDK_VERSION: "18.1.sdk"
      run: |
        set -e
        bash ./install_dep.sh

    - name: Config cmake
      working-directory: ${{ github.workspace }}/NunchukSDK/
      run: |
        set -e
        cmake -B build -G Xcode -DCMAKE_TOOLCHAIN_FILE=./ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_WARN_DEPRECATED=FALSE

    - name: Build
      working-directory: ${{ github.workspace }}/NunchukSDK/build
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        #xcodebuild -sdk iphoneos -arch arm64 -scheme nunchukSDK -configuration Release
        xcodebuild archive -project nunchukWalletSDK.xcodeproj -scheme nunchukSDK -sdk iphoneos -arch arm64 -archivePath "$PWD/out" SKIP_INSTALL=NO -configuration Release

    - name: Upload Artifact
      uses: 'actions/upload-artifact@v4'
      with:
        name: upload
        path: ${{ github.workspace }}/NunchukSDK/build
