name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-ios:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install tools
      run: |
        brew list automake || brew install automake
        brew list libtool || brew install libtool
        brew list make || brew install make

    - name: Set the correct Xcode version
      run: |
        sudo xcode-select --switch /Applications/Xcode_16.1.app

    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install || echo "Xcode Command Line Tools are already installed"

    - name: Accept Xcode License
      run: sudo xcodebuild -license accept

    - name: Restore submodules
      id: cache-sub
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/NunchukSDK/libnunchuk
        key: cache-sub-9

    - name: Update submodules
      working-directory: ${{ github.workspace }}
      if: steps.cache-sub.outputs.cache-hit != 'true'
      env:
        GH_LOGIN: ${{ secrets.GH_LOGIN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GL_LOGIN: ${{ secrets.GL_LOGIN }}
        GL_TOKEN: ${{ secrets.GL_TOKEN }}
      run: |
        echo -e "machine github.com login $GH_LOGIN password $GH_TOKEN\nmachine gitlab.com login $GL_LOGIN password $GL_TOKEN" > ~/.netrc
        set -e
        git submodule update --init --recursive --depth 1

    - name: Install deps
      working-directory: ${{ github.workspace }}
      if: steps.cache-sub.outputs.cache-hit != 'true'
      env:
        IOS_SDK_VERSION: "18.1.sdk"
      run: |
        set -e
        bash ./install_dep.sh

    - name: Save cache submodules
      if: always() && steps.cache-sub.outputs.cache-hit != 'true'
      id: cache-sub-save
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/NunchukSDK/libnunchuk
        key: ${{ steps.cache-sub.outputs.cache-primary-key }}
    
    - name: Restore cmake
      id: cache-cmake
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/NunchukSDK/build
        key: cache-cmake-9

    - name: Config cmake
      if: steps.cache-cmake.outputs.cache-hit != 'true'
      working-directory: ${{ github.workspace }}/NunchukSDK/
      run: |
        set -e
        cmake -B build -G Xcode -DCMAKE_TOOLCHAIN_FILE=./ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_WARN_DEPRECATED=FALSE

    - name: Save cache cmake
      if: always() && steps.cache-cmake.outputs.cache-hit != 'true'
      id: cache-cmake-save
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/NunchukSDK/build
        key: ${{ steps.cache-cmake.outputs.cache-primary-key }}

    - name: Build
      working-directory: ${{ github.workspace }}/NunchukSDK/build
      run: |
        xcodebuild -sdk iphoneos -arch arm64 -scheme nunchuk -configuration Release

    - name: Upload Artifact
      uses: 'actions/upload-artifact@v3'
      with:
        name: upload
        path: ${{ github.workspace }}/NunchukSDK/build
